Include alpha and beta in release title regex

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -25,7 +25,12 @@ jobs:
 
       - name: Check release title format
         run: |
-          TITLE_VERSION_REGEX="^v[0-9]+\.[0-9]+\.[0-9]+$"
+          if [[ -z "$RELEASE_TITLE" ]]; then
+            echo "Release title cannot be empty"
+            exit 1
+          fi
+
+          TITLE_VERSION_REGEX="^v[0-9]+\.[0-9]+\.[0-9]+(-alpha|-beta)?$"
           if [[ ! $RELEASE_TITLE =~ $TITLE_VERSION_REGEX ]]; then
             echo "Invalid release title format: $RELEASE_TITLE"
             exit 1
@@ -35,7 +40,12 @@ jobs:
 
       - name: Check release tag format
         run: |
-          TAG_VERSION_REGEX="^[0-9]+\.[0-9]+\.[0-9]+$"
+          if [[ -z "$RELEASE_TAG" ]]; then
+            echo "Release tag cannot be empty"
+            exit 1
+          fi
+
+          TAG_VERSION_REGEX="^[0-9]+\.[0-9]+\.[0-9]+(-alpha|-beta)?$"
           if [[ ! $RELEASE_TAG =~ $TAG_VERSION_REGEX ]]; then
             echo "Invalid release tag format: $RELEASE_TAG"
             exit 1
